### ISSUE TITLE
Alternative type parameters for Mock

### ISSUE THREAD

**Issue by hasparus** [dethcrypto/earl#134]
Currently, given function type `F`, a type of a mock of this function is `Mock<Parameters<F>, ReturnType<F>>`. Wouldn't it be more convenient to write `Mock<F>`?

**Comment by krzkaczor** [comment]
Yup! Totally makes sense. `mockFn` already supports both signatures.

**Comment by hasparus** [comment]
I don't think there's a way to support both signatures for `Mock`. (I mean, I tried declaration merging without success.) This would be a breaking change, right?

**Comment by krzkaczor** [comment]
What if we introduce another type like MockFn that would take fn instead? I am not sure if having only function type variant is strictly better option that the current situation.

**Comment by krzkaczor** [comment]
Released in https://github.com/dethcrypto/earl/releases/tag/earljs%400.1.11
