### ISSUE TITLE
[dethcrypto/earl] Run failed: all-contributors - master (....)

### ISSUE THREAD

**Issue by moltar** [dethcrypto/earl#154]
Keep getting these emails from GH actions from this repo.

Kinda strange, since I haven't really contributed anything, other than the other issue of mine (#152).

![screenshot-20211224T112635-tjqaILlD](https://user-images.githubusercontent.com/491247/147316211-cf7fa3d0-3f9c-4823-9fc0-d6e31136b31b.png)

**Comment by krzkaczor** [comment]
Thanks for the report. Just a rogue bot trying to ruin Christmas spirit 🤖 🎄 

Dealt in https://github.com/dethcrypto/earl/pull/155
