### ISSUE TITLE
Add `toBeTruthy`, `toBeFalsy` / `toBeDefined` validators 

### ISSUE THREAD

**Issue by Marik-D** [dethcrypto/earl#85]

**Comment by sz-piotr** [comment]
How about `toBeNullish`? It could cover `null` and `undefined`

**Comment by krzkaczor** [comment]
Let's sum up. You're proposing new validators / matchers:

- toBeTruthy / expect.truthy - matches truthy values !!val === true
- toBeFalsy / expect.falsy - matches falsy values !val === true
- toBeDefined / expect.defined - matches everything other than null and undefined
- toBeNullish / expect.nullish - matches null and undefined

@Marik-D @sz-piotr if you have any suggestions to the behavior or naming now's the time.

**Comment by Kamrulhasan12345** [comment]
Any updates on this?
